/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "inverter.v:1.1-8.10" *)
module inverter(a, y);
  (* src = "inverter.v:2.11-2.12" *)
  wire _0_;
  (* src = "inverter.v:3.12-3.13" *)
  wire _1_;
  (* src = "inverter.v:2.11-2.12" *)
  input a;
  wire a;
  (* src = "inverter.v:3.12-3.13" *)
  output y;
  wire y;
  assign _1_ = ~_0_;
  assign _0_ = a;
  assign y = _1_;
endmodule
