/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "and.v:1.1-9.10" *)
module and_gate(a, b, y);
  (* src = "and.v:2.11-2.12" *)
  wire _0_;
  (* src = "and.v:3.11-3.12" *)
  wire _1_;
  (* src = "and.v:4.12-4.13" *)
  wire _2_;
  (* src = "and.v:2.11-2.12" *)
  input a;
  wire a;
  (* src = "and.v:3.11-3.12" *)
  input b;
  wire b;
  (* src = "and.v:4.12-4.13" *)
  output y;
  wire y;
  assign _2_ = _1_ & _0_;
  assign _1_ = b;
  assign _0_ = a;
  assign y = _2_;
endmodule
